# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yunzhong/Study/Homework/stats232B/project1/Project1-AOGDetector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yunzhong/Study/Homework/stats232B/project1/Project1-AOGDetector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yunzhong/Study/Homework/stats232B/project1/Project1-AOGDetector/CMakeFiles /Users/yunzhong/Study/Homework/stats232B/project1/Project1-AOGDetector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yunzhong/Study/Homework/stats232B/project1/Project1-AOGDetector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Entryd

# Build rule for target.
Entryd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Entryd
.PHONY : Entryd

# fast build rule for target.
Entryd/fast:
	$(MAKE) -f CMakeFiles/Entryd.dir/build.make CMakeFiles/Entryd.dir/build
.PHONY : Entryd/fast

#=============================================================================
# Target rules for targets named RGM_Cored

# Build rule for target.
RGM_Cored: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RGM_Cored
.PHONY : RGM_Cored

# fast build rule for target.
RGM_Cored/fast:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/build
.PHONY : RGM_Cored/fast

src/core/AOGrammar.o: src/core/AOGrammar.cpp.o

.PHONY : src/core/AOGrammar.o

# target to build an object file
src/core/AOGrammar.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/AOGrammar.cpp.o
.PHONY : src/core/AOGrammar.cpp.o

src/core/AOGrammar.i: src/core/AOGrammar.cpp.i

.PHONY : src/core/AOGrammar.i

# target to preprocess a source file
src/core/AOGrammar.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/AOGrammar.cpp.i
.PHONY : src/core/AOGrammar.cpp.i

src/core/AOGrammar.s: src/core/AOGrammar.cpp.s

.PHONY : src/core/AOGrammar.s

# target to generate assembly for a file
src/core/AOGrammar.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/AOGrammar.cpp.s
.PHONY : src/core/AOGrammar.cpp.s

src/core/FeaturePyramid.o: src/core/FeaturePyramid.cpp.o

.PHONY : src/core/FeaturePyramid.o

# target to build an object file
src/core/FeaturePyramid.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/FeaturePyramid.cpp.o
.PHONY : src/core/FeaturePyramid.cpp.o

src/core/FeaturePyramid.i: src/core/FeaturePyramid.cpp.i

.PHONY : src/core/FeaturePyramid.i

# target to preprocess a source file
src/core/FeaturePyramid.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/FeaturePyramid.cpp.i
.PHONY : src/core/FeaturePyramid.cpp.i

src/core/FeaturePyramid.s: src/core/FeaturePyramid.cpp.s

.PHONY : src/core/FeaturePyramid.s

# target to generate assembly for a file
src/core/FeaturePyramid.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/FeaturePyramid.cpp.s
.PHONY : src/core/FeaturePyramid.cpp.s

src/core/Inference.o: src/core/Inference.cpp.o

.PHONY : src/core/Inference.o

# target to build an object file
src/core/Inference.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Inference.cpp.o
.PHONY : src/core/Inference.cpp.o

src/core/Inference.i: src/core/Inference.cpp.i

.PHONY : src/core/Inference.i

# target to preprocess a source file
src/core/Inference.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Inference.cpp.i
.PHONY : src/core/Inference.cpp.i

src/core/Inference.s: src/core/Inference.cpp.s

.PHONY : src/core/Inference.s

# target to generate assembly for a file
src/core/Inference.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Inference.cpp.s
.PHONY : src/core/Inference.cpp.s

src/core/Parameters.o: src/core/Parameters.cpp.o

.PHONY : src/core/Parameters.o

# target to build an object file
src/core/Parameters.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Parameters.cpp.o
.PHONY : src/core/Parameters.cpp.o

src/core/Parameters.i: src/core/Parameters.cpp.i

.PHONY : src/core/Parameters.i

# target to preprocess a source file
src/core/Parameters.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Parameters.cpp.i
.PHONY : src/core/Parameters.cpp.i

src/core/Parameters.s: src/core/Parameters.cpp.s

.PHONY : src/core/Parameters.s

# target to generate assembly for a file
src/core/Parameters.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Parameters.cpp.s
.PHONY : src/core/Parameters.cpp.s

src/core/ParseTree.o: src/core/ParseTree.cpp.o

.PHONY : src/core/ParseTree.o

# target to build an object file
src/core/ParseTree.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/ParseTree.cpp.o
.PHONY : src/core/ParseTree.cpp.o

src/core/ParseTree.i: src/core/ParseTree.cpp.i

.PHONY : src/core/ParseTree.i

# target to preprocess a source file
src/core/ParseTree.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/ParseTree.cpp.i
.PHONY : src/core/ParseTree.cpp.i

src/core/ParseTree.s: src/core/ParseTree.cpp.s

.PHONY : src/core/ParseTree.s

# target to generate assembly for a file
src/core/ParseTree.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/ParseTree.cpp.s
.PHONY : src/core/ParseTree.cpp.s

src/core/Patchwork.o: src/core/Patchwork.cpp.o

.PHONY : src/core/Patchwork.o

# target to build an object file
src/core/Patchwork.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Patchwork.cpp.o
.PHONY : src/core/Patchwork.cpp.o

src/core/Patchwork.i: src/core/Patchwork.cpp.i

.PHONY : src/core/Patchwork.i

# target to preprocess a source file
src/core/Patchwork.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Patchwork.cpp.i
.PHONY : src/core/Patchwork.cpp.i

src/core/Patchwork.s: src/core/Patchwork.cpp.s

.PHONY : src/core/Patchwork.s

# target to generate assembly for a file
src/core/Patchwork.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Patchwork.cpp.s
.PHONY : src/core/Patchwork.cpp.s

src/core/Rectangle.o: src/core/Rectangle.cpp.o

.PHONY : src/core/Rectangle.o

# target to build an object file
src/core/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Rectangle.cpp.o
.PHONY : src/core/Rectangle.cpp.o

src/core/Rectangle.i: src/core/Rectangle.cpp.i

.PHONY : src/core/Rectangle.i

# target to preprocess a source file
src/core/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Rectangle.cpp.i
.PHONY : src/core/Rectangle.cpp.i

src/core/Rectangle.s: src/core/Rectangle.cpp.s

.PHONY : src/core/Rectangle.s

# target to generate assembly for a file
src/core/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Rectangle.cpp.s
.PHONY : src/core/Rectangle.cpp.s

src/core/Timer.o: src/core/Timer.cpp.o

.PHONY : src/core/Timer.o

# target to build an object file
src/core/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Timer.cpp.o
.PHONY : src/core/Timer.cpp.o

src/core/Timer.i: src/core/Timer.cpp.i

.PHONY : src/core/Timer.i

# target to preprocess a source file
src/core/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Timer.cpp.i
.PHONY : src/core/Timer.cpp.i

src/core/Timer.s: src/core/Timer.cpp.s

.PHONY : src/core/Timer.s

# target to generate assembly for a file
src/core/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/Timer.cpp.s
.PHONY : src/core/Timer.cpp.s

src/core/UtilFile.o: src/core/UtilFile.cpp.o

.PHONY : src/core/UtilFile.o

# target to build an object file
src/core/UtilFile.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilFile.cpp.o
.PHONY : src/core/UtilFile.cpp.o

src/core/UtilFile.i: src/core/UtilFile.cpp.i

.PHONY : src/core/UtilFile.i

# target to preprocess a source file
src/core/UtilFile.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilFile.cpp.i
.PHONY : src/core/UtilFile.cpp.i

src/core/UtilFile.s: src/core/UtilFile.cpp.s

.PHONY : src/core/UtilFile.s

# target to generate assembly for a file
src/core/UtilFile.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilFile.cpp.s
.PHONY : src/core/UtilFile.cpp.s

src/core/UtilGeneric.o: src/core/UtilGeneric.cpp.o

.PHONY : src/core/UtilGeneric.o

# target to build an object file
src/core/UtilGeneric.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilGeneric.cpp.o
.PHONY : src/core/UtilGeneric.cpp.o

src/core/UtilGeneric.i: src/core/UtilGeneric.cpp.i

.PHONY : src/core/UtilGeneric.i

# target to preprocess a source file
src/core/UtilGeneric.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilGeneric.cpp.i
.PHONY : src/core/UtilGeneric.cpp.i

src/core/UtilGeneric.s: src/core/UtilGeneric.cpp.s

.PHONY : src/core/UtilGeneric.s

# target to generate assembly for a file
src/core/UtilGeneric.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilGeneric.cpp.s
.PHONY : src/core/UtilGeneric.cpp.s

src/core/UtilLog.o: src/core/UtilLog.cpp.o

.PHONY : src/core/UtilLog.o

# target to build an object file
src/core/UtilLog.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilLog.cpp.o
.PHONY : src/core/UtilLog.cpp.o

src/core/UtilLog.i: src/core/UtilLog.cpp.i

.PHONY : src/core/UtilLog.i

# target to preprocess a source file
src/core/UtilLog.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilLog.cpp.i
.PHONY : src/core/UtilLog.cpp.i

src/core/UtilLog.s: src/core/UtilLog.cpp.s

.PHONY : src/core/UtilLog.s

# target to generate assembly for a file
src/core/UtilLog.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilLog.cpp.s
.PHONY : src/core/UtilLog.cpp.s

src/core/UtilMath.o: src/core/UtilMath.cpp.o

.PHONY : src/core/UtilMath.o

# target to build an object file
src/core/UtilMath.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilMath.cpp.o
.PHONY : src/core/UtilMath.cpp.o

src/core/UtilMath.i: src/core/UtilMath.cpp.i

.PHONY : src/core/UtilMath.i

# target to preprocess a source file
src/core/UtilMath.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilMath.cpp.i
.PHONY : src/core/UtilMath.cpp.i

src/core/UtilMath.s: src/core/UtilMath.cpp.s

.PHONY : src/core/UtilMath.s

# target to generate assembly for a file
src/core/UtilMath.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilMath.cpp.s
.PHONY : src/core/UtilMath.cpp.s

src/core/UtilOpencv.o: src/core/UtilOpencv.cpp.o

.PHONY : src/core/UtilOpencv.o

# target to build an object file
src/core/UtilOpencv.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilOpencv.cpp.o
.PHONY : src/core/UtilOpencv.cpp.o

src/core/UtilOpencv.i: src/core/UtilOpencv.cpp.i

.PHONY : src/core/UtilOpencv.i

# target to preprocess a source file
src/core/UtilOpencv.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilOpencv.cpp.i
.PHONY : src/core/UtilOpencv.cpp.i

src/core/UtilOpencv.s: src/core/UtilOpencv.cpp.s

.PHONY : src/core/UtilOpencv.s

# target to generate assembly for a file
src/core/UtilOpencv.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilOpencv.cpp.s
.PHONY : src/core/UtilOpencv.cpp.s

src/core/UtilString.o: src/core/UtilString.cpp.o

.PHONY : src/core/UtilString.o

# target to build an object file
src/core/UtilString.cpp.o:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilString.cpp.o
.PHONY : src/core/UtilString.cpp.o

src/core/UtilString.i: src/core/UtilString.cpp.i

.PHONY : src/core/UtilString.i

# target to preprocess a source file
src/core/UtilString.cpp.i:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilString.cpp.i
.PHONY : src/core/UtilString.cpp.i

src/core/UtilString.s: src/core/UtilString.cpp.s

.PHONY : src/core/UtilString.s

# target to generate assembly for a file
src/core/UtilString.cpp.s:
	$(MAKE) -f CMakeFiles/RGM_Cored.dir/build.make CMakeFiles/RGM_Cored.dir/src/core/UtilString.cpp.s
.PHONY : src/core/UtilString.cpp.s

src/main/Entry.o: src/main/Entry.cpp.o

.PHONY : src/main/Entry.o

# target to build an object file
src/main/Entry.cpp.o:
	$(MAKE) -f CMakeFiles/Entryd.dir/build.make CMakeFiles/Entryd.dir/src/main/Entry.cpp.o
.PHONY : src/main/Entry.cpp.o

src/main/Entry.i: src/main/Entry.cpp.i

.PHONY : src/main/Entry.i

# target to preprocess a source file
src/main/Entry.cpp.i:
	$(MAKE) -f CMakeFiles/Entryd.dir/build.make CMakeFiles/Entryd.dir/src/main/Entry.cpp.i
.PHONY : src/main/Entry.cpp.i

src/main/Entry.s: src/main/Entry.cpp.s

.PHONY : src/main/Entry.s

# target to generate assembly for a file
src/main/Entry.cpp.s:
	$(MAKE) -f CMakeFiles/Entryd.dir/build.make CMakeFiles/Entryd.dir/src/main/Entry.cpp.s
.PHONY : src/main/Entry.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Entryd"
	@echo "... RGM_Cored"
	@echo "... src/core/AOGrammar.o"
	@echo "... src/core/AOGrammar.i"
	@echo "... src/core/AOGrammar.s"
	@echo "... src/core/FeaturePyramid.o"
	@echo "... src/core/FeaturePyramid.i"
	@echo "... src/core/FeaturePyramid.s"
	@echo "... src/core/Inference.o"
	@echo "... src/core/Inference.i"
	@echo "... src/core/Inference.s"
	@echo "... src/core/Parameters.o"
	@echo "... src/core/Parameters.i"
	@echo "... src/core/Parameters.s"
	@echo "... src/core/ParseTree.o"
	@echo "... src/core/ParseTree.i"
	@echo "... src/core/ParseTree.s"
	@echo "... src/core/Patchwork.o"
	@echo "... src/core/Patchwork.i"
	@echo "... src/core/Patchwork.s"
	@echo "... src/core/Rectangle.o"
	@echo "... src/core/Rectangle.i"
	@echo "... src/core/Rectangle.s"
	@echo "... src/core/Timer.o"
	@echo "... src/core/Timer.i"
	@echo "... src/core/Timer.s"
	@echo "... src/core/UtilFile.o"
	@echo "... src/core/UtilFile.i"
	@echo "... src/core/UtilFile.s"
	@echo "... src/core/UtilGeneric.o"
	@echo "... src/core/UtilGeneric.i"
	@echo "... src/core/UtilGeneric.s"
	@echo "... src/core/UtilLog.o"
	@echo "... src/core/UtilLog.i"
	@echo "... src/core/UtilLog.s"
	@echo "... src/core/UtilMath.o"
	@echo "... src/core/UtilMath.i"
	@echo "... src/core/UtilMath.s"
	@echo "... src/core/UtilOpencv.o"
	@echo "... src/core/UtilOpencv.i"
	@echo "... src/core/UtilOpencv.s"
	@echo "... src/core/UtilString.o"
	@echo "... src/core/UtilString.i"
	@echo "... src/core/UtilString.s"
	@echo "... src/main/Entry.o"
	@echo "... src/main/Entry.i"
	@echo "... src/main/Entry.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

